#Clothes
#First
image monika 1a_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 1b_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 1c_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 1d_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 1e_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 1f_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 1g_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 1h_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 1i_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 1j_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 1k_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 1l_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 1m_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 1n_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 1o_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 1p_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 1q_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 1r_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 1s_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 1t_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 1u_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 1v_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_1.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 2a_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 2b_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 2c_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 2d_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 2e_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 2f_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 2g_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 2h_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 2i_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 2j_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 2k_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 2l_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 2m_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 2n_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 2o_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 2p_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 2q_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 2r_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 2s_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 2t_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 2u_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 2v_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_2.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 3a_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 3b_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 3c_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 3d_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 3e_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 3f_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 3g_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 3h_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 3i_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 3j_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 3k_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 3l_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 3m_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 3n_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 3o_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 3p_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 3q_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 3r_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 3s_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 3t_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 3u_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 3v_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_3.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 4a_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 4b_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 4c_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 4d_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 4e_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 4f_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 4g_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 4h_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 4i_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 4j_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 4k_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 4l_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 4m_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 4n_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 4o_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 4p_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 4q_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 4r_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 4s_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 4t_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 4u_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 4v_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_4.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 5a_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_5.png")
image monika 5b_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_6.png")

image monika 6a_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_7.png")

image monika 7a_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_8.png")
image monika 7b_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_9.png")
image monika 7c_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_10.png")
image monika 7d_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_11.png")
image monika 7e_dateday01 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1_12.png")


#Second
image monika 1a_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 1b_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 1c_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 1d_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 1e_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 1f_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 1g_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 1h_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 1i_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 1j_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 1k_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 1l_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 1m_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 1n_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 1o_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 1p_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 1q_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 1r_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 1s_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 1t_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 1u_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 1v_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_1.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 2a_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 2b_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 2c_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 2d_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 2e_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 2f_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 2g_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 2h_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 2i_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 2j_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 2k_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 2l_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 2m_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 2n_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 2o_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 2p_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 2q_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 2r_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 2s_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 2t_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 2u_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 2v_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_2.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 3a_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 3b_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 3c_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 3d_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 3e_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 3f_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 3g_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 3h_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 3i_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 3j_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 3k_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 3l_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 3m_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 3n_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 3o_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 3p_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 3q_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 3r_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 3s_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 3t_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 3u_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 3v_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_3.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 4a_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 4b_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 4c_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 4d_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 4e_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 4f_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 4g_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 4h_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 4i_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 4j_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 4k_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 4l_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 4m_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 4n_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 4o_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 4p_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 4q_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 4r_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 4s_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 4t_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 4u_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 4v_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_4.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 5a_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_5.png")
image monika 5b_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_6.png")

image monika 6a_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_7.png")

image monika 7a_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_8.png")
image monika 7b_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_9.png")
image monika 7c_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_10.png")
image monika 7d_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_11.png")
image monika 7e_dateday02 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2_12.png")


#Third
image monika 1a_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 1b_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 1c_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 1d_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 1e_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 1f_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 1g_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 1h_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 1i_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 1j_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 1k_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 1l_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 1m_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 1n_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 1o_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 1p_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 1q_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 1r_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 1s_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 1t_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 1u_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 1v_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_1.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 2a_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 2b_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 2c_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 2d_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 2e_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 2f_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 2g_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 2h_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 2i_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 2j_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 2k_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 2l_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 2m_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 2n_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 2o_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 2p_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 2q_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 2r_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 2s_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 2t_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 2u_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 2v_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_2.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 3a_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 3b_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 3c_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 3d_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 3e_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 3f_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 3g_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 3h_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 3i_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 3j_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 3k_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 3l_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 3m_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 3n_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 3o_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 3p_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 3q_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 3r_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 3s_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 3t_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 3u_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 3v_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_3.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 4a_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 4b_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 4c_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 4d_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 4e_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 4f_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 4g_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 4h_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 4i_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 4j_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 4k_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 4l_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 4m_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 4n_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 4o_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 4p_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 4q_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 4r_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 4s_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 4t_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 4u_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 4v_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_4.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 5a_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_5.png")
image monika 5b_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_6.png")

image monika 6a_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_7.png")

image monika 7a_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_8.png")
image monika 7b_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_9.png")
image monika 7c_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_10.png")
image monika 7d_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_11.png")
image monika 7e_dateday03 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3_12.png")


#Fourth
image monika 1a_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 1b_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 1c_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 1d_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 1e_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 1f_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 1g_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 1h_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 1i_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 1j_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 1k_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 1l_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 1m_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 1n_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 1o_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 1p_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 1q_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 1r_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 1s_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 1t_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 1u_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 1v_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_1.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 2a_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 2b_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 2c_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 2d_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 2e_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 2f_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 2g_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 2h_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 2i_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 2j_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 2k_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 2l_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 2m_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 2n_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 2o_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 2p_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 2q_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 2r_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 2s_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 2t_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 2u_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 2v_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_2.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 3a_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 3b_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 3c_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 3d_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 3e_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 3f_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 3g_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 3h_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 3i_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 3j_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 3k_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 3l_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 3m_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 3n_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 3o_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 3p_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 3q_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 3r_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 3s_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 3t_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 3u_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 3v_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_3.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 4a_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 4b_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 4c_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 4d_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 4e_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 4f_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 4g_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 4h_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 4i_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 4j_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 4k_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 4l_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 4m_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 4n_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 4o_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 4p_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 4q_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 4r_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/r.png")
image monika 4s_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 4t_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 4u_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 4v_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_4.png", (0, 0), "Submods/DateDay/images/monika/v.png")

image monika 5a_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_5.png")
image monika 5b_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_6.png")

image monika 6a_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_7.png")

image monika 7a_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_8.png")
image monika 7b_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_9.png")
image monika 7c_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_10.png")
image monika 7d_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_11.png")
image monika 7e_dateday04 = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/4_12.png")


#school
#Monika Sprites
# Original Monika sprites a-r
image monika 1a_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 1b_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 1c_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 1d_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 1e_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 1f_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 1g_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 1h_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 1i_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 1j_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 1k_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 1l_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 1m_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 1n_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 1o_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 1p_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 1q_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 1r_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/r.png")

#New sprites
image monika 1s_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 1t_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 1u_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 1v_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/v.png")

# Original Monika sprites a-r
image monika 2a_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 2b_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 2c_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 2d_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 2e_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 2f_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 2g_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 2h_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 2i_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 2j_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 2k_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 2l_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 2m_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 2n_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 2o_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 2p_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 2q_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 2r_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/r.png")

#New Sprites
image monika 2s_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 2t_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 2u_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 2v_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/1l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/v.png")

# Original Monika sprites a-r
image monika 3a_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 3b_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 3c_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 3d_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 3e_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 3f_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 3g_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 3h_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 3i_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 3j_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 3k_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 3l_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 3m_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 3n_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 3o_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 3p_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 3q_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 3r_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/r.png")

#New Sprites
image monika 3s_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 3t_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 3u_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 3v_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/1r.png", (0, 0), "Submods/DateDay/images/monika/v.png")

# Original Monika sprites a-r
image monika 4a_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/a.png")
image monika 4b_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/b.png")
image monika 4c_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/c.png")
image monika 4d_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/d.png")
image monika 4e_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/e.png")
image monika 4f_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/f.png")
image monika 4g_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/g.png")
image monika 4h_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/h.png")
image monika 4i_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/i.png")
image monika 4j_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/j.png")
image monika 4k_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/k.png")
image monika 4l_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/l.png")
image monika 4m_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/m.png")
image monika 4n_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/n.png")
image monika 4o_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/o.png")
image monika 4p_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/p.png")
image monika 4q_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/q.png")
image monika 4r_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/r.png")

#New Sprites
image monika 4s_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/s.png")
image monika 4t_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/t.png")
image monika 4u_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/u.png")
image monika 4v_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/2l.png", (0, 0), "Submods/DateDay/images/monika/2r.png", (0, 0), "Submods/DateDay/images/monika/v.png")

# Original Monika sprites a-r
image monika 5a_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3a.png")
image monika 5b_dateday = im.Composite((960, 960), (0, 0), "Submods/DateDay/images/monika/3b.png")
